version: 2

jobs:
  build:
    docker:
      - image: circleci/python:2-jessie
    steps:
      - checkout
      - run: echo "Hello World"
  test:
    docker:
      - image: circleci/python:2-jessie
    steps:
      - checkout
      - run: echo "Hello World"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
        requires:
          - build
